# -*- coding: utf-8 -*-
"""KNN_Assignment13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18ZrYBx-ggXTaZR3Vaq3EyCA4XDIlv2L6
"""

#Social_Networks_Ads.csv

"""**Importing the libraries**"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from scipy.sparse import csr_matrix
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
from sklearn.preprocessing import StandardScaler
import os



"""**Importing the dataset**"""

drive.mount('/content/drive')
os.chdir('/content/drive/My Drive/Task_7')
df = pd.read_csv('Social_Network_Ads.csv')
df.head()

df["Gender"]=df["Gender"].map({"Male":1,"Female":2})

df.drop("User ID",axis=1,inplace=True)

"""**Splitting the dataset into the Training set and Test set**"""

x=df.drop(columns=["Purchased"])
y=df["Purchased"]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=8)

"""**Feature Scaling**"""

sc =StandardScaler()
sc.fit(x_train)
x_train= sc.transform(x_train)
sc.fit(x_test)
x_test= sc.transform(x_test)
x.shape

"""**Fitting K-NN to the Training set**"""

k = 4
#Train Model and Predict 
model = KNeighborsClassifier(n_neighbors = k).fit(x_train,y_train)
model

"""**Predicting the Test set results**"""

yhat = model.predict(x_test)
yhat

from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, model.predict(x_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))

"""**Making the Confusion Matrix**"""

print(metrics.confusion_matrix(y_test, yhat))
# Printing the precision and recall, among other metrics
print(metrics.classification_report(y_test, yhat))