# -*- coding: utf-8 -*-
"""Logistic_Regression_Assignment12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aRULCeETIAcpWKF7q5-BUWuvWcONXhZg
"""

# Social_Network_Ads.csv

"""This dataset contains information of users in a social network. Those informations are the user id the gender the age and the estimated salary. A car company has just launched their brand new luxury SUV. And we're trying to see which of these users of the social network are going to buy this brand new SUV And the last column here tells If yes or no the user bought this SUV we are going to build a model that is going to predict if a user is going to buy or not the SUV based on two variables which are going to be the age and the estimated salary. So our matrix of feature is only going to be these two columns. We want to find some correlations between the age and the estimated salary of a user and his decision to purchase yes or no the SUV.

**Step 1 | Data Pre-Processing**

**Importing the Libraries**
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from scipy.sparse import csr_matrix
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
import seaborn as sns
import os
from google.colab import drive
from sklearn.preprocessing import StandardScaler

"""**Importing the dataset**"""

drive.mount('/content/drive')
os.chdir('/content/drive/My Drive/Task_7')
df = pd.read_csv('Social_Network_Ads.csv')
df.head()

df.head()

df["Gender"]=df["Gender"].map({"Male":1,"Female":2})

"""**Splitting the dataset into the Training set and Test set**"""

x=df.drop(columns=["User ID","Purchased"])
y=df["Purchased"]

x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=4)
print ('Train set:', x_train.shape,  y_train.shape)
print ('Test set:', x_test.shape,  y_test.shape)

"""**Feature Scaling**"""

sc =StandardScaler()
sc.fit(x_train)
x_train= sc.transform(x_train)
sc.fit(x_test)
x_test= sc.transform(x_test)
x.shape

"""**Step 2 | Logistic Regression Model**

The library for this job which is going to be the linear model library and it is called linear because the logistic regression is a linear classifier which means that here since we're in two dimensions, our two categories of users are going to be separated by a straight line. Then import the logistic regression class. Next we will create a new object from this class which is going to be our classifier that we are going to fit on our training set.

**Fitting Logistic Regression to the Training set**
"""

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

"""**Step 3 | Predection**"""

y_pred = model.predict(x_test)
y_pred

"""**Step 4 | Evaluating The Predection**

We predicted the test results and now we will evaluate if our logistic regression model learned and understood correctly. So this confusion matrix is going to contain the correct predictions that our model made on the set as well as the incorrect predictions.

**Making the Confusion Matrix**
"""

from sklearn import metrics
print("Mean Absolute Error:",metrics.mean_absolute_error(y_test,y_pred))
print("Mean Squared Error:",metrics.mean_squared_error(y_test,y_pred))
print("Root Mean Squared Error:",np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

"""**Visualization**"""

plt.figure(figsize=(10,5))
plt.plot(x,y,"s")
plt.plot(x,model.predict(x))
plt.show()